#- name: Install Apache
 - name: install apache2
   package:
     name: apache2
     state: present
   become: yes

 - name: copy index.html
   ansible.builtin.copy:
     src: "/home/tk/.ansible/index.html"
     dest: "/var/www/html/index.html"
   become: yes
